import { Event } from "@/interfaces";

// Helpers to build dates relative to today
function daysFromNow(days: number, hour = 9): Date {
  const d = new Date();
  d.setHours(hour, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d;
}

function dateStr(days: number): string {
  return daysFromNow(days).toISOString().split("T")[0];
}

function ms(days: number, hour = 0): number {
  return daysFromNow(days, hour).getTime();
}

const now = Date.now();

export const dummyEvents: Event[] = [
  // ── Today ────────────────────────────────────────────────────────────────
  {
    id: "evt_001",
    organizationId: "org_greenearth",
    title: "City Park Cleanup",
    description: "Community effort to clean litter and restore the park.",
    location: "Central City Park",
    address: "1200 Park Avenue, Springfield, IL 62701",
    date: dateStr(0),
    startTime: "09:00",
    endTime: "13:00",
    shifts: ["shf_001"],
    coordinators: ["user_001"],
    collaborators: ["user_002", "user_003"],
    organizer: {
      name: "Maria Rodriguez",
      title: "Volunteer Coordinator",
      phone: "+1 (217) 555-0142",
      email: "maria.r@greenearth.org",
    },
    status: "active",
    eventCode: "PARK-2024",
    createdAt: ms(-10),
    updatedAt: ms(-1),
  },

  // ── Future ───────────────────────────────────────────────────────────────
  {
    id: "evt_002",
    organizationId: "org_greenearth",
    title: "Beach Plastic Sweep",
    description: "Remove plastic waste from the shoreline.",
    location: "Sunset Beach",
    address: "800 Coastal Highway, Newport, CA 92663",
    date: dateStr(5),
    startTime: "08:00",
    endTime: "12:00",
    shifts: ["shf_002"],
    coordinators: ["user_004"],
    collaborators: [],
    organizer: {
      name: "James Okafor",
      title: "Event Organizer",
      phone: "+1 (949) 555-0187",
      email: "james.o@greenearth.org",
    },
    status: "published",
    eventCode: "BEACH-SWEEP",
    createdAt: ms(-8),
    updatedAt: ms(-2),
  },
  {
    id: "evt_006",
    organizationId: "org_greenearth",
    title: "River Restoration Day",
    description: "Remove debris and restore riverbanks.",
    location: "Bluewater River Park",
    address: "340 River Road, Riverside, IL 60546",
    date: dateStr(10),
    startTime: "07:00",
    endTime: "11:00",
    shifts: ["shf_006"],
    coordinators: ["user_010"],
    collaborators: [],
    organizer: {
      name: "Priya Menon",
      title: "Conservation Lead",
      phone: "+1 (708) 555-0231",
      email: "priya.m@greenearth.org",
    },
    status: "published",
    eventCode: "RIVER-REST",
    createdAt: ms(-5),
    updatedAt: ms(-1),
  },
  {
    id: "evt_007",
    organizationId: "org_eduhelp",
    title: "After School Tutoring",
    description: "Provide tutoring support for students.",
    location: "Lincoln Community Center",
    address: "55 Lincoln Ave, Evanston, IL 60201",
    date: dateStr(14),
    startTime: "15:00",
    endTime: "18:00",
    shifts: ["shf_007"],
    coordinators: ["user_011"],
    collaborators: ["user_012"],
    organizer: {
      name: "Sandra Lee",
      title: "Program Director",
      phone: "+1 (847) 555-0309",
      email: "sandra.l@eduhelp.org",
    },
    status: "published",
    eventCode: "TUTOR-SCH",
    createdAt: ms(-6),
    updatedAt: ms(-1),
  },
  {
    id: "evt_008",
    organizationId: "org_healthfirst",
    title: "Community Health Fair",
    description: "Assist with booths and registration.",
    location: "Downtown Civic Plaza",
    address: "100 Civic Center Dr, Chicago, IL 60601",
    date: dateStr(21),
    startTime: "09:00",
    endTime: "17:00",
    shifts: ["shf_008"],
    coordinators: ["user_013"],
    collaborators: [],
    organizer: {
      name: "Dr. Kevin Park",
      title: "Health Fair Coordinator",
      phone: "+1 (312) 555-0418",
      email: "kevin.p@healthfirst.org",
    },
    status: "published",
    eventCode: "HEALTH-FAIR",
    createdAt: ms(-4),
    updatedAt: ms(-1),
  },
  {
    id: "evt_009",
    organizationId: "org_citycare",
    title: "Winter Coat Drive",
    description: "Collect and sort donated winter coats.",
    location: "City Hall Lobby",
    address: "211 E Monroe St, Springfield, IL 62701",
    date: dateStr(30),
    startTime: "10:00",
    endTime: "14:00",
    shifts: ["shf_009"],
    coordinators: ["user_014"],
    collaborators: [],
    organizer: {
      name: "Angela Torres",
      title: "Community Outreach Manager",
      phone: "+1 (217) 555-0527",
      email: "angela.t@citycare.org",
    },
    status: "draft",
    eventCode: "COAT-DRV",
    createdAt: ms(-3),
    updatedAt: ms(-1),
  },

  // ── Past ─────────────────────────────────────────────────────────────────
  {
    id: "evt_003",
    organizationId: "org_foodbank",
    title: "Food Bank Sorting Day",
    description: "Sort and package donated food items.",
    location: "Metro Food Bank Warehouse",
    address: "456 Main Street, Springfield, IL 62701",
    date: dateStr(-7),
    startTime: "10:00",
    endTime: "14:00",
    shifts: ["shf_003"],
    coordinators: ["user_005"],
    collaborators: ["user_006"],
    organizer: {
      name: "Carlos Reyes",
      title: "Warehouse Coordinator",
      phone: "+1 (217) 555-0613",
      email: "carlos.r@metrofoodbank.org",
    },
    status: "completed",
    eventCode: "FOOD-SORT",
    createdAt: ms(-20),
    updatedAt: ms(-7),
  },
  {
    id: "evt_004",
    organizationId: "org_animalaid",
    title: "Animal Shelter Support",
    description: "Help feed and care for shelter animals.",
    location: "Happy Paws Shelter",
    address: "78 Elm Street, Oak Park, IL 60302",
    date: dateStr(-14),
    startTime: "09:00",
    endTime: "13:00",
    shifts: ["shf_004"],
    coordinators: ["user_007"],
    collaborators: [],
    organizer: {
      name: "Rachel Kim",
      title: "Shelter Manager",
      phone: "+1 (708) 555-0724",
      email: "rachel.k@happypaws.org",
    },
    status: "completed",
    eventCode: "PAWS-CARE",
    createdAt: ms(-30),
    updatedAt: ms(-14),
  },
  {
    id: "evt_005",
    organizationId: "org_citycare",
    title: "Neighborhood Tree Planting",
    description: "Plant new trees across the neighborhood.",
    location: "Maple Street District",
    address: "Maple St & 5th Ave, Springfield, IL 62702",
    date: dateStr(-21),
    startTime: "08:00",
    endTime: "12:00",
    shifts: ["shf_005"],
    coordinators: ["user_008"],
    collaborators: ["user_009"],
    organizer: {
      name: "Tom Nguyen",
      title: "Urban Forestry Lead",
      phone: "+1 (217) 555-0835",
      email: "tom.n@citycare.org",
    },
    status: "cancelled",
    eventCode: "TREE-PLT",
    createdAt: ms(-40),
    updatedAt: ms(-21),
  },
  {
    id: "evt_010",
    organizationId: "org_greenearth",
    title: "Urban Garden Build",
    description: "Build raised beds for community garden.",
    location: "Eastside Community Garden",
    address: "920 Garden Lane, Chicago, IL 60619",
    date: dateStr(-60),
    startTime: "08:00",
    endTime: "12:00",
    shifts: ["shf_010"],
    coordinators: ["user_015"],
    collaborators: [],
    organizer: {
      name: "Diane Foster",
      title: "Garden Project Lead",
      phone: "+1 (773) 555-0946",
      email: "diane.f@greenearth.org",
    },
    status: "completed",
    eventCode: "GARDEN-BLD",
    createdAt: ms(-75),
    updatedAt: ms(-60),
  },
];
